acquire g++ first

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -1,17 +1,35 @@
-name: Run tests
+name: Run Tests
 
 on:
-  push:
-    branches: [ "main" ]
   pull_request:
-    branches: [ "main" ]
+    types: [opened, synchronize, reopened]
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
-    - name: make
-      run: cd test && make
+    - uses: actions/checkout@v3
+
+    - name: Install dependencies
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y g++
+
+    - name: Run Makefile
+      run: |
+        cd tests
+        make build
+        make run
+      continue-on-error: false
+      id: makefile
+
+    - name: Check Makefile result
+      run: |
+        if [ ${{ steps.makefile.outcome }} == 'success' ]; then
+          echo "Tests passed :-)"
+          exit 0
+        else
+          echo "Tests failed :-("
+          exit 1
+        fi
